version: '3.1'

services:
  db:
    image: 'bitnami/mongodb:4.2'
    restart: always
    environment:
      - MONGODB_USERNAME=$DB_USER
      - MONGODB_PASSWORD=$DB_PASSWORD
      - MONGODB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGODB_DATABASE=$DB_NAME
    volumes:
      - mongo_vol:/bitnami
  app:
    env_file: .env
    depends_on:
      - db
    image: $CI_REGISTRY_IMAGE:$IMAGE_TAG
    ports:
      - ${SERVER_PORT_EXPOSE:-3001}:3001
      - ${CLIENT_PORT_EXPOSE:-3000}:3000
    volumes:
      - upload_vol:/app/upload

volumes:
  mongo_vol:
  upload_vol:
