version: '3.1'

services:

  mongodb:
    image: 'bitnami/mongodb:4.2'
    restart: always
    environment:
      - MONGODB_USERNAME=$DB_USER
      - MONGODB_PASSWORD=$DB_PASSWORD
      - MONGODB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGODB_DATABASE=$DB_NAME
    ports:
      - 27017:27017
    volumes:
      - 'mongo_vol:/bitnami'

volumes:
  mongo_vol:
